theme = "soho"
baseURL = "https://evansdianga.com"
title = "Evans Dianga"
languageCode = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true

[params]
author = "Evans Dianga"
description = "Dev Blog"
## Set one of:
# gravatar = "soho@example.com"
profilePicture = "https://avatars.githubusercontent.com/u/6088118?v=4"

copyright = "Evans Dianga"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
 themeColor = "#2671a3"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/blog.css"]
customJs = ["js/blog.js"]

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://linkedin.com/in/evansdianga"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/evansdianga"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://x.com/evansdianga"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"
  [[menu.main]]

  [[menu.main]]
  name = "Tags"
  weight = 200
  identifier = "tags"
  url = "/tags/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
      unsafe = true